### ISSUE TITLE
메뉴 화면전환 시 CSR이 동작하지 않습니다.

### ISSUE THREAD

**Issue by handoo** [HakMukSa/GameWagon-Main-Front#1]
# 이슈
메뉴 화면전환 시 CSR이 동작하지 않습니다.

### ASIS
- NAV클릭 시 화면이 깜빡이는 현상이 있습니다.
- 네트워크 탭을 보면 새로고침 되는것을 확인할 수 있습니다. 

### TOBE
- 화면이 깜빡이는 현상이 없어야 합니다.
- 링크클릭으로 화면전환을 할 때에도 실제로 바뀌는 부분만 랜더링이 되어야 합니다.

**Comment by chapsaldduk** [comment]
안녕하세요 해당 부분은 기능 구현이 되어있지 않습니다 구현 후 PR 오픈 후 코멘트 남기겠습니다 감사합니다

**Comment by dhtmdgkr123** [comment]
@chapsaldduk 케이스 관련하여 영상 첨부 합니다
![case_1](https://github.com/HakMukSa/GameWagon-Main-Front/assets/27611405/aad85eca-4962-4c0e-b9e9-2aa645528c2b)

**Comment by dhtmdgkr123** [comment]
Fixed by #2
